name: myTestAutomation

on:
  push:
    branches: [ "main" ]

jobs:

  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello message
        run : echo "Hello, world!"

  bye:
    runs-on: ubuntu-latest
    
    steps:
      - name: Bye message
        run : echo "Bye, bye!"

     
