name: myTestAutomation

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  hello:
    runs-on: ubuntu-latest
    
    steps:
      #- uses: actions/checkout@v3

      - name: Hello message
        run : echo "Hello, world!"


  bye:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Bye message
        run : echo "Bye, bye!"

     
